### ISSUE TITLE
Very nice

### ISSUE THREAD

**Issue by corywalker** [cznic/wl#1]
This looks very nice! I got a chance to mess around with the test cases but not much more than that today. It looks like you load a test source file from "testdata/corpus" and parse that.

I just found this today:

https://github.com/rljacobson/FoxySheep

Looks like a fairly complete parser for WL, but it's written in Antlr4 and needs some language specific bindings. The language specific helpers essentially handle follow sets and some other utilities.

**Comment by cznic** [comment]
Repository is now public.

However, maybe you want to use your local copy anyway. The reason is that the parser in this repo will probably just build the AST (conversion to FullForms might be nice too.). But I think in your project you want to take advantage of inserting actions in the parser. Of course the AST can be walked post parsing, but it's sometimes very convenient to perform some handling right  in the parser. Moreover, inserting actions in the .yy file is easy as the `yy` tool handles some [magic names](https://godoc.org/github.com/cznic/yy#hdr-Magic_names) specially, usage example in [cc](https://github.com/cznic/cc/blob/b98d4a758e7bcca3eabdbc1ae0139db6e52252ab/parser.yy#L795).

There are still more operators not yet implemented than the opposite. Not sure how far I can get this weekend, but today I'm mostly occupied by my daily job (delivering a huge project at Monday), it may consume also my free time tomorrow.

**Comment by corywalker** [comment]
Sounds good. By the way, I would recommend removing the long comment in prec.go as it is clearly a copy/paste from the website.

**Comment by cznic** [comment]
You're right, thanks for the heads up. Will do in a couple of minutes.

**Comment by cznic** [comment]
Done.

**Comment by cznic** [comment]
@corywalker About 100 operators not yet handled, but there's some progress. Guestimated using http://reference.wolfram.com/language/tutorial/OperatorInputForms.html.

**Comment by corywalker** [comment]
Thanks! I really like the nice support for unicode in the parser. Even operators can be unicode! This was one of the features I found lacking in the parser I was using before. Why use Go if you don't support Unicode, right? :P

I switched Expreduce to use your repo by default. I created a branch of my own within your repo which I'll make changes to if needed. You've already fixed the few changes I needed to make.

I also really like the helpful error messages. Before I was just returning "Syntax error". These errors actually explain what the issue is.

**Comment by cznic** [comment]
Great!

I've commented in one of yours commits just minutes ago, please don't miss the important info there.

> I also really like the helpful error messages. 

Me too. I was not sure how the non-ASCII stuff will be handled, but it seem to work ;-)

(Note the symbols at the end of the list)
```
In[1]:= a[%]
/dev/stdin:1:3: unexpected '%', expected expression list or one of ['!', '(', '-', ']', '{', ++, --, <<, \@, identifier, integer, pattern, real, slot, string, √, ∫]
```
